### 결제 취소
POST http://localhost:8080/api/refunds
Content-Type: application/json

{
  "paymentId" : 18,
  "refundType": "PARTIAL_REFUND",
  "quantity": 1,
  "cancelAmount": 5000
}

### 환불 목록 조회
GET http://localhost:8080/api/refunds
Content-Type: application/json

### 환불 상세 조회
GET http://localhost:8080/api/refunds/3
Content-Type: application/json