### 예약 생성
POST http://localhost:8080/api/reservations
Content-Type: application/json
access: eyJhbGciOiJIUzI1NiJ9.eyJ0b2tlblR5cGUiOiJhY2Nlc3MiLCJlbWFpbCI6InVzZXJ0ZXN0QGV4YW1wbGUuY29tIiwicm9sZXMiOlsiUk9MRV9VU0VSIl0sImlhdCI6MTcxODc3NDQ4NCwiZXhwIjoxNzE4Nzc1MDg0fQ.DFSIuEq6ortpaDmgkAgCV_zIbJuoXyQgVBM0wKYdm9Q

{
  "user_id" : 1,
  "lesson_id" : 2,
  "quantity" : 1
}

### 특정 예약 조회
GET http://localhost:8080/api/reservations/10
Content-Type: application/json
access: eyJhbGciOiJIUzI1NiJ9.eyJ0b2tlblR5cGUiOiJhY2Nlc3MiLCJlbWFpbCI6InVzZXJ0ZXN0QGV4YW1wbGUuY29tIiwicm9sZXMiOlsiUk9MRV9VU0VSIl0sImlhdCI6MTcxODY5Nzc0OCwiZXhwIjoxNzE4Njk4MzQ4fQ.VXkdmP5F5gZqHcur3xgz9oDF97joKdpnymh9Sq63f8c


### 특정 예약 강사 취소
PATCH http://localhost:8080/api/reservations/13/cancel
Content-Type: application/json
access: eyJhbGciOiJIUzI1NiJ9.eyJ0b2tlblR5cGUiOiJhY2Nlc3MiLCJlbWFpbCI6InVzZXJ0ZXN0QGV4YW1wbGUuY29tIiwicm9sZXMiOlsiUk9MRV9VU0VSIl0sImlhdCI6MTcxODc3NTU2NiwiZXhwIjoxNzE4Nzc2MTY2fQ.N1Q9WgxuapDuGg0EIYuYJx3tFZW7r3HBXSMbZL_ekCk

### 모든 예약 조회
GET http://localhost:8080/api/reservations
Content-Type: application/json
access: eyJhbGciOiJIUzI1NiJ9.eyJ0b2tlblR5cGUiOiJhY2Nlc3MiLCJlbWFpbCI6InVzZXJ0ZXN0QGV4YW1wbGUuY29tIiwicm9sZXMiOlsiUk9MRV9VU0VSIl0sImlhdCI6MTcxODM1Mzc5MywiZXhwIjoxNzE4MzU0MzkzfQ.n1zmAyjr2B4h8p3soXz-sPo1V_uXXcFvZPAtEm2-Ztk

### 모든 예약 조회 필터링 by user_id
GET http://localhost:8080/api/reservations?user_id=2
Content-Type: application/json
access: eyJhbGciOiJIUzI1NiJ9.eyJ0b2tlblR5cGUiOiJhY2Nlc3MiLCJlbWFpbCI6InVzZXJ0ZXN0QGV4YW1wbGUuY29tIiwicm9sZXMiOlsiUk9MRV9VU0VSIl0sImlhdCI6MTcxODM1NTA1OCwiZXhwIjoxNzE4MzU1NjU4fQ.y57avbKNN_zkN8fLfGVwWJDZCgKI-Gw6Mlnlx14BKiY

### 모든 예약 조회 필터링 by lesson_id
GET http://localhost:8080/api/reservations?lesson_id=2
Content-Type: application/json
access: eyJhbGciOiJIUzI1NiJ9.eyJ0b2tlblR5cGUiOiJhY2Nlc3MiLCJlbWFpbCI6InVzZXJ0ZXN0QGV4YW1wbGUuY29tIiwicm9sZXMiOlsiUk9MRV9VU0VSIl0sImlhdCI6MTcxODM1NTI5OSwiZXhwIjoxNzE4MzU1ODk5fQ.sfxuN3bseWxbV1ZxF9dxoYH3suUxiS5S9i-3V5rbyIw

### 모든 예약 조회 필터링 by status
GET http://localhost:8080/api/reservations?status=PENDING
Content-Type: application/json
access: eyJhbGciOiJIUzI1NiJ9.eyJ0b2tlblR5cGUiOiJhY2Nlc3MiLCJlbWFpbCI6InVzZXJ0ZXN0QGV4YW1wbGUuY29tIiwicm9sZXMiOlsiUk9MRV9VU0VSIl0sImlhdCI6MTcxODM1NTUwNCwiZXhwIjoxNzE4MzU2MTA0fQ.q9UHmja95WAae5tGpykAuuCkWVk5K0ARWZGpgam26DQ

### 모든 예약 조회 필터링 by all
GET http://localhost:8080/api/reservations?user_id=1&lesson_id=2&status=PENDING
Content-Type: application/json
access: eyJhbGciOiJIUzI1NiJ9.eyJ0b2tlblR5cGUiOiJhY2Nlc3MiLCJlbWFpbCI6InVzZXJ0ZXN0QGV4YW1wbGUuY29tIiwicm9sZXMiOlsiUk9MRV9VU0VSIl0sImlhdCI6MTcxODM1NTUwNCwiZXhwIjoxNzE4MzU2MTA0fQ.q9UHmja95WAae5tGpykAuuCkWVk5K0ARWZGpgam26DQ