### 예약 생성
POST http://localhost:8080/api/reservations
Content-Type: application/json
access: eyJhbGciOiJIUzI1NiJ9.eyJ0b2tlblR5cGUiOiJhY2Nlc3MiLCJlbWFpbCI6InVzZXJ0ZXN0QGV4YW1wbGUuY29tIiwicm9sZXMiOlsiUk9MRV9VU0VSIl0sImlhdCI6MTcxODk3NTE5NiwiZXhwIjoxNzE4OTc1Nzk2fQ.PdWNbYfnCCMHXWoQmeziMlTKP8-xm_lv4GCVVcbxNDg

{
  "user_id" : 1,
  "lesson_id" : 2,
  "quantity" : 1
}

### 예약 생성
POST http://13.125.180.170:8080/api/reservations
Content-Type: application/json
access: eyJhbGciOiJIUzI1NiJ9.eyJ0b2tlblR5cGUiOiJhY2Nlc3MiLCJlbWFpbCI6InVzZXJ0ZXN0QGV4YW1wbGUuY29tIiwicm9sZXMiOlsiUk9MRV9VU0VSIl0sImlhdCI6MTcxODk3MTc1NSwiZXhwIjoxNzE4OTcyMzU1fQ.Lvw3rhKbfql42_mKmIv9DWoCOTkpwyqnfVXg-_DmN8M

{
  "user_id" : 7,
  "lesson_id" : 28,
  "quantity" : 2
}

### 예약 생성
POST http://ec2-3-38-165-201.ap-northeast-2.compute.amazonaws.com:8080/api/reservations
Content-Type: application/json
access: eyJhbGciOiJIUzI1NiJ9.eyJ0b2tlblR5cGUiOiJhY2Nlc3MiLCJlbWFpbCI6InVzZXJ0ZXN0QGV4YW1wbGUuY29tIiwicm9sZXMiOlsiUk9MRV9VU0VSIl0sImlhdCI6MTcxODk3Mzc3NCwiZXhwIjoxNzE4OTc0Mzc0fQ.1jkK3cj15wwIwYe-nHYRLZzPYBwNLd1N7IJTcExB5Wg

{
  "user_id" : 7,
  "lesson_id" : 28,
  "quantity" : 2
}

### 특정 예약 조회
GET http://localhost:8080/api/reservations/10
Content-Type: application/json
access: eyJhbGciOiJIUzI1NiJ9.eyJ0b2tlblR5cGUiOiJhY2Nlc3MiLCJlbWFpbCI6InVzZXJ0ZXN0QGV4YW1wbGUuY29tIiwicm9sZXMiOlsiUk9MRV9VU0VSIl0sImlhdCI6MTcxODc4MjE0NywiZXhwIjoxNzE4NzgyNzQ3fQ.fxdS4oyXOXHDULRIBF9lUTqz28jHrScs6b4VxeiV-58


### 특정 예약 강사 취소
PATCH http://localhost:8080/api/reservations/13/cancel
Content-Type: application/json
access: eyJhbGciOiJIUzI1NiJ9.eyJ0b2tlblR5cGUiOiJhY2Nlc3MiLCJlbWFpbCI6InVzZXJ0ZXN0QGV4YW1wbGUuY29tIiwicm9sZXMiOlsiUk9MRV9VU0VSIl0sImlhdCI6MTcxODc3NTU2NiwiZXhwIjoxNzE4Nzc2MTY2fQ.N1Q9WgxuapDuGg0EIYuYJx3tFZW7r3HBXSMbZL_ekCk

### 모든 예약 조회
GET http://localhost:8080/api/reservations
Content-Type: application/json
access: eyJhbGciOiJIUzI1NiJ9.eyJ0b2tlblR5cGUiOiJhY2Nlc3MiLCJlbWFpbCI6InVzZXJ0ZXN0QGV4YW1wbGUuY29tIiwicm9sZXMiOlsiUk9MRV9VU0VSIl0sImlhdCI6MTcxODM1Mzc5MywiZXhwIjoxNzE4MzU0MzkzfQ.n1zmAyjr2B4h8p3soXz-sPo1V_uXXcFvZPAtEm2-Ztk

### 모든 예약 조회 필터링 by user_id
GET http://localhost:8080/api/reservations?user_id=2
Content-Type: application/json
access: eyJhbGciOiJIUzI1NiJ9.eyJ0b2tlblR5cGUiOiJhY2Nlc3MiLCJlbWFpbCI6InVzZXJ0ZXN0QGV4YW1wbGUuY29tIiwicm9sZXMiOlsiUk9MRV9VU0VSIl0sImlhdCI6MTcxODM1NTA1OCwiZXhwIjoxNzE4MzU1NjU4fQ.y57avbKNN_zkN8fLfGVwWJDZCgKI-Gw6Mlnlx14BKiY

### 모든 예약 조회 필터링 by lesson_id
GET http://localhost:8080/api/reservations?lesson_id=2
Content-Type: application/json
access: eyJhbGciOiJIUzI1NiJ9.eyJ0b2tlblR5cGUiOiJhY2Nlc3MiLCJlbWFpbCI6InVzZXJ0ZXN0QGV4YW1wbGUuY29tIiwicm9sZXMiOlsiUk9MRV9VU0VSIl0sImlhdCI6MTcxODM1NTI5OSwiZXhwIjoxNzE4MzU1ODk5fQ.sfxuN3bseWxbV1ZxF9dxoYH3suUxiS5S9i-3V5rbyIw

### 모든 예약 조회 필터링 by status
GET http://localhost:8080/api/reservations?status=PENDING
Content-Type: application/json
access: eyJhbGciOiJIUzI1NiJ9.eyJ0b2tlblR5cGUiOiJhY2Nlc3MiLCJlbWFpbCI6InVzZXJ0ZXN0QGV4YW1wbGUuY29tIiwicm9sZXMiOlsiUk9MRV9VU0VSIl0sImlhdCI6MTcxODM1NTUwNCwiZXhwIjoxNzE4MzU2MTA0fQ.q9UHmja95WAae5tGpykAuuCkWVk5K0ARWZGpgam26DQ

### 모든 예약 조회 필터링 by all
GET http://localhost:8080/api/reservations?user_id=1&lesson_id=2&status=PENDING
Content-Type: application/json
access: eyJhbGciOiJIUzI1NiJ9.eyJ0b2tlblR5cGUiOiJhY2Nlc3MiLCJlbWFpbCI6InVzZXJ0ZXN0QGV4YW1wbGUuY29tIiwicm9sZXMiOlsiUk9MRV9VU0VSIl0sImlhdCI6MTcxODM1NTUwNCwiZXhwIjoxNzE4MzU2MTA0fQ.q9UHmja95WAae5tGpykAuuCkWVk5K0ARWZGpgam26DQ